
import React, { Component } from 'react';


export default class Agreement extends Component {
  
    render(){
        return <div class="Section0" style={{"layout-grid":"15.6000pt"}}><p class="MsoNormal" align="center" style={{"text-align":"center"}}><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"15.0000pt",
        "mso-font-kerning":"1.0000pt"}}><font face="等线">用户监测数据许可</font><font face="等线">协议</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"15.0000pt",
        "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">甲方：用户</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">乙方：北京雪迪龙科技股份有限公司</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">根据本协议，甲方同意授予乙方基于智能环境监测设备</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">运行和服务</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">而监测、</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">传输</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">与使用甲方数据信息的</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">权利。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">现就具体事项约定如下：</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">一、许可对象：监测平台在运行过程中搜集到的用户基本信息、环保实时监测数据与其他周边信息。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">二、许可范围：</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>1</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">、甲方</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">任何</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">格式</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">在</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">设备或系统</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">上</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">监测、</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">传输、存储或处理的所有数据、软件、设备、文本、图像、视频、音频、照片、第三方应用程序、信息、材料</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">等</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">乙方自身的</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">数据和信息不</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">属于此列；</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>2</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">、仅指企业信息，本许可协议不涉及国标</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>GBT 35273-2017《信息安全技术个人信息安全规范》</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">规范的个人信息。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">三、授权使用用途：包括但不限于</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>1</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">、甲方环境监测实时信息、备份留存、汇总信息及可视化成果；</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>2</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">、为应对环保监管机关检查而提供符合监管要求数据信息；</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">3、向其他公共事务管理机构如市场监督管理局、商标局、证监会等提供或司法机关依法调取；</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">3、为配合国家环境保护标准制定或修订提供相应数据信息；</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">4、商业研究与应用：环保大数据的研究及商业化应用。 </font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">四、修改与转让</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>1</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">、乙方</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">可能通过在网站上传修改后的版本或者其他方式通知</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">甲方</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">发布本协议的修改版本，包括协议中所提及的文件和政策。除非更新后的版本、文件或政策另有规定，修改的条款将于发布或通知后生效。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">甲方</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">需要定期在网上查阅这些条款。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">甲方</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">在条款修改生效后继续使用服务将被视为接受修改后的条款</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">；</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">2、不可转让。未经乙方事先书面同意，甲方不得转让或以其他方式将本协议的全部或部分转让给任何第三方，包括甲方的关联方。乙方可能会在未经甲方同意的情况下向关联方转让或转移本协议项下的任何权利或义务。在转让生效前，乙方会通过网站通知或其他途径告知甲方。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">五、合规使用</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>1</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">、账户：甲方需要谨慎保存企业账号与密码，所提供的资料与事实不符或所提供的资料已变更而未更新导致乙方无法为用户提供或进一步提供服务，乙方不因此承担任何责任；</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>2</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">、篡改：鉴于智能化操作平台的特殊性，乙方无义务审核是否甲方本企业使用该组账号及密码，仅审核账号及密码是否与数据库中保存的一致，只要任何人输入的账号及密码与数据库中保存的一致，即可凭借该组账号及密码登陆，由此导致数据发生错误或遭篡改行为即使并非其企业用户所为，乙方将不承担因此而产生的任何责任。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">六、知识产权</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">1、乙方拥有</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">本协议项下</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">硬件设计，</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">服务（包括任何基础软件程序及其所有部分、复制和修改）、服务衍生品</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">、监测数据研究</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">以及由</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">乙方</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">开发或交付的任何内容的所有权、知识产权和权益</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">；</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>2</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">、甲方</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">不得、也不能使得或允许其他人（</font>a）修改、变更服务或制造服务的衍生品；（b）对服务进行反汇编、反编译、反向工程、复制服务的任何部分，或应用其他任何程序来获得服务中所包含的任何软件的源代码；（c）分发、转售、再许可、或转让服务</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">七、保密规定</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">1、保密期限为双方合作结束之后期限2年。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">双方承诺在保密期限内，</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">未经对方事先书面许可，一方</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">不会</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">不符合本</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">协议规定目的</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">，</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">自己或允许他人使用保密信息的全部或任何部分</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">；</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>2</span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">、除了上述第二条、第三条乙方不得透露甲方任何非官方信息，乙方有权对整个用户数据库进行技术分析并对已进行分析、整理后的用户数据库进行商业上的利用。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">八、争议解决</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}><font face="等线">双方同意本协议的签订地为北京市昌平区，并同意将因本协议引起的或与本协议有关的任何争议提交合同签订地有管辖权的法院诉讼解决（包括与非合同义务有关的任何争议或索赔）。</font></span><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}></span></p><p class="MsoNormal"><span style={{'mso-spacerun':'yes',"font-family":"等线","font-size":"10.5000pt",
              "mso-font-kerning":"1.0000pt"}}>&nbsp;</span></p></div>
    }
}